import "dotenv/config";
import assert from "node:assert/strict";
import { once } from "node:events";
import { spawnSync } from "node:child_process";
import { PrismaClient } from "@prisma/client";
import bcrypt from "bcrypt";
import jwt from "jsonwebtoken";

const dbUrl = new URL(process.env.DATABASE_URL!);
if (!["localhost", "127.0.0.1", "[::1]"].includes(dbUrl.hostname)) throw new Error("Email auth tests require a local PostgreSQL host");
const database = `fantasy_email_auth_test_${Date.now()}`;
const setup = new PrismaClient();
await setup.$executeRawUnsafe(`CREATE DATABASE "${database}"`);
dbUrl.pathname = "/" + database;
process.env.DATABASE_URL = dbUrl.toString();
process.env.RESEND_API_KEY = "test-only-no-real-delivery";
process.env.EMAIL_FROM = "Fantasy <test@example.invalid>";
process.env.FRONTEND_URL = "https://fantasy.example.invalid";
const nativeFetch = globalThis.fetch;
const mail: Array<{ to: string[]; text: string; subject: string }> = [];
let deliveryFails = false;
globalThis.fetch = async (input, init) => {
  if (String(input) === "https://api.resend.com/emails") {
    if (deliveryFails) return new Response("{}", { status: 503 });
    mail.push(JSON.parse(String(init?.body)));
    return new Response(JSON.stringify({ id: "test-message" }), { status: 200 });
  }
  return nativeFetch(input, init);
};
let server: ReturnType<typeof import("../src/app.js").app.listen> | undefined;
let db: PrismaClient | undefined;
try {
  const migrated = spawnSync(process.execPath, ["node_modules/prisma/build/index.js", "migrate", "deploy", "--schema", "backend/prisma/schema.prisma"], { env: process.env, encoding: "utf8" });
  assert.equal(migrated.status, 0, migrated.stderr + migrated.stdout);
  const { app } = await import("../src/app.js");
  const { prisma } = await import("../src/lib/prisma.js");
  db = prisma;
  const { env } = await import("../src/config/env.js");
  const { hashEmailSecret, takeAuthLimit } = await import("../src/services/auth-email.js");
  server = app.listen(0, "127.0.0.1");
  await once(server, "listening");
  const base = `http://127.0.0.1:${(server.address() as { port: number }).port}/api`;
  const request = async (path: string, body?: unknown, status = 200, token?: string) => {
    const response = await nativeFetch(base + path, { method: body ? "POST" : "GET", headers: { "Content-Type": "application/json", "Accept-Language": "uk", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
    const json = await response.json();
    assert.equal(response.status, status, `${path}: ${JSON.stringify(json)}`);
    return json;
  };
  const clearLimits = () => prisma.authRateLimit.deleteMany();
  const ageChallenge = async (email: string, purpose: string) => {
    await prisma.emailChallenge.update({ where: { email_purpose: { email, purpose } }, data: { expiresAt: new Date(Date.now() + (purpose === "REGISTER" ? 10 : 30) * 60_000 - 61_000) } });
    await clearLimits();
  };
  const code = () => mail.at(-1)!.text.match(/\b\d{6}\b/)![0];
  const resetToken = () => new URL(mail.at(-1)!.text.match(/https:\/\/\S+/)![0]).hash.slice(1);
  const input = { email: "player@example.invalid", password: "Original-Password-123", name: "Player" };
  const pending = await request("/auth/register", { ...input, email: " PLAYER@example.invalid " }, 202);
  assert.equal(pending.token, undefined);
  assert.equal(await prisma.user.count(), 0);
  const firstCode = code();
  const stored = await prisma.emailChallenge.findFirstOrThrow();
  assert.notEqual(stored.secretHash, firstCode);
  assert.notEqual(stored.passwordHash, input.password);
  await request("/auth/login", input, 401);
  await request("/auth/resend-verification", { email: input.email }, 429);
  const wrongCode = firstCode === "000000" ? "111111" : "000000";
  for (let i = 0; i < 5; i++) await request("/auth/verify-email", { email: input.email, code: wrongCode }, 400);
  await request("/auth/verify-email", { email: input.email, code: firstCode }, 400);
  assert.equal((await prisma.emailChallenge.findFirstOrThrow()).attempts, 5);
  await ageChallenge(input.email, "REGISTER");
  await request("/auth/resend-verification", { email: input.email });
  const nextCode = code();
  if (firstCode !== nextCode) await request("/auth/verify-email", { email: input.email, code: firstCode }, 400);
  const registered = await request("/auth/verify-email", { email: input.email, code: nextCode }, 201);
  assert.ok(registered.token);
  assert.equal(await prisma.user.count(), 1);
  assert.equal(await prisma.fantasyTeam.count(), 1);
  assert.equal(await prisma.leagueMember.count(), 1);
  assert.ok((await prisma.user.findFirstOrThrow()).emailVerifiedAt);
  assert.equal((await prisma.emailChallenge.findFirstOrThrow()).passwordHash, null);
  await request("/auth/verify-email", { email: input.email, code: nextCode }, 400);
  await request("/auth/me", undefined, 200, registered.token);
  await clearLimits();
  await request("/auth/register", input, 409);
  await clearLimits();
  const known = await request("/auth/forgot-password", { email: input.email });
  const firstReset = new URLSearchParams(resetToken()).get("token")!;
  const mailCount = mail.length;
  const unknown = await request("/auth/forgot-password", { email: "unknown@example.invalid" });
  assert.deepEqual(known, unknown);
  assert.equal(mail.length, mailCount);
  await request("/auth/forgot-password", { email: input.email }, 429);
  await ageChallenge(input.email, "RESET");
  await request("/auth/forgot-password", { email: input.email });
  const token = new URLSearchParams(resetToken()).get("token")!;
  await request("/auth/reset-password", { email: input.email, token: firstReset, password: "Replacement-123" }, 400);
  await request("/auth/reset-password", { email: "other@example.invalid", token, password: "Replacement-123" }, 400);
  await request("/auth/reset-password", { email: input.email, token, password: "short" }, 400);
  const oldSession = jwt.sign({}, env.jwtSecret, { subject: registered.user.id, expiresIn: "1h" });
  await request("/auth/me", undefined, 200, oldSession);
  await request("/auth/reset-password", { email: input.email, token, password: "Replacement-123" });
  await request("/auth/reset-password", { email: input.email, token, password: "Replacement-456" }, 400);
  await request("/auth/me", undefined, 401, registered.token);
  await request("/auth/me", undefined, 401, oldSession);
  await request("/auth/login", input, 401);
  const newSession = await request("/auth/login", { email: input.email, password: "Replacement-123" });
  await request("/auth/me", undefined, 200, newSession.token);
  await clearLimits();
  const expiredInput = { ...input, email: "expired@example.invalid" };
  await request("/auth/register", expiredInput, 202);
  const expiredCode = code();
  await prisma.emailChallenge.update({ where: { email_purpose: { email: expiredInput.email, purpose: "REGISTER" } }, data: { expiresAt: new Date(Date.now() - 1) } });
  await request("/auth/verify-email", { email: expiredInput.email, code: expiredCode }, 400);
  await ageChallenge(input.email, "RESET");
  await request("/auth/forgot-password", { email: input.email });
  const expiredToken = new URLSearchParams(resetToken()).get("token")!;
  await prisma.emailChallenge.update({ where: { email_purpose: { email: input.email, purpose: "RESET" } }, data: { expiresAt: new Date(Date.now() - 1) } });
  await request("/auth/reset-password", { email: input.email, token: expiredToken, password: "Replacement-456" }, 400);
  // Parallel consumption must create exactly one account and one usable session.
  const raceInput = { ...input, email: "race@example.invalid" };
  await clearLimits();
  await request("/auth/register", raceInput, 202);
  const raceCode = code();
  const concurrent = await Promise.all([0, 1].map(() => nativeFetch(base + "/auth/verify-email", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ email: raceInput.email, code: raceCode }) })));
  assert.deepEqual(concurrent.map(r => r.status).sort(), [201, 400]);
  assert.equal(await prisma.user.count({ where: { email: raceInput.email } }), 1);
  await clearLimits();
  deliveryFails = true;
  await request("/auth/register", { ...input, email: "failed@example.invalid" }, 503);
  assert.equal(await prisma.user.count({ where: { email: "failed@example.invalid" } }), 0);
  deliveryFails = false;
  env.resendApiKey = undefined;
  await request("/auth/register", { ...input, email: "unconfigured@example.invalid" }, 503);
  env.resendApiKey = "test-only";
  const legacy = await prisma.user.create({ data: { email: "legacy@example.invalid", name: "Existing", passwordHash: await bcrypt.hash(input.password, 4) } });
  assert.equal(legacy.emailVerifiedAt, null);
  await request("/auth/login", { email: legacy.email, password: input.password });
  assert.notEqual(hashEmailSecret(input.email, "REGISTER", "123456"), hashEmailSecret(input.email, "RESET", "123456"));
  const limitResults = await Promise.allSettled(Array.from({ length: 8 }, () => takeAuthLimit("test", "same-address", 5, 60 * 60_000)));
  assert.equal(limitResults.filter(result => result.status === "fulfilled").length, 5);
  console.log("PASS: registration, attempts, resend, expiry, concurrent verification, recovery, reuse, session revocation, legacy accounts, delivery failures and shared limits");
} finally {
  globalThis.fetch = nativeFetch;
  if (server) await new Promise<void>((resolve, reject) => server!.close(error => error ? reject(error) : resolve()));
  await db?.$disconnect();
  // database is generated above from a fixed prefix and digits, never user input.
  await setup.$executeRawUnsafe(`DROP DATABASE "${database}" WITH (FORCE)`);
  await setup.$disconnect();
}
