import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';
import jwt from 'jsonwebtoken';
import { mock } from 'node:test';
import { once } from 'node:events';
import { marketDatesForWeek, marketIsOpen } from '../src/services/market-schedule.js';
const url=new URL(process.env.DATABASE_URL!);
assert.ok(['localhost','127.0.0.1'].includes(url.hostname));
const database=`fantasy_market_${Date.now()}`;
const setup=new PrismaClient();await setup.$executeRawUnsafe(`CREATE DATABASE "${database}"`);await setup.$disconnect();
url.pathname='/'+database;process.env.DATABASE_URL=url.toString();
const migration=spawnSync(process.execPath,['node_modules/prisma/build/index.js','migrate','deploy','--schema','backend/prisma/schema.prisma'],{env:process.env,encoding:'utf8'});assert.equal(migration.status,0,migration.stderr);
mock.timers.enable({apis:['Date'],now:new Date('2026-10-01T10:00:00Z')});
const {prisma}=await import('../src/lib/prisma.js');
const {assertOpenMarket}=await import('../src/services/gameweeks.js');
const {app}=await import('../src/app.js');const server=app.listen(0,'127.0.0.1');await once(server,'listening');
const request=async(path:string,id:string,method='GET',body?:unknown)=>{
 const token=jwt.sign({},process.env.JWT_SECRET!,{subject:id});const r=await fetch(`http://127.0.0.1:${(server.address() as {port:number}).port}/api${path}`,{method,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});return {status:r.status,data:await r.json()};
};
try {
 const admin=await prisma.user.create({data:{name:'Admin',email:'admin@example.invalid',passwordHash:'unused',role:'ADMIN'}});
 const user=await prisma.user.create({data:{name:'User',email:'user@example.invalid',passwordHash:'unused',fantasyTeam:{create:{name:'Team',budget:40000}}}});
 const club=await prisma.club.create({data:{name:'Club'}});const player=await prisma.player.create({data:{name:'Player',clubId:club.id,number:1,position:'FIELD_PLAYER',role:'ALA',price:2000}});
 let week=(await request('/gameweeks/current',user.id)).data;
 assert.equal(week.marketIsOpen,true);assert.equal(week.marketOpenAt,'2026-09-28T06:00:00.000Z');assert.equal(week.deadlineAt,'2026-10-02T17:00:00.000Z');
 assert.equal((await request('/admin/market',user.id,'PATCH',{gameweekId:week.id,mode:'CLOSED'})).status,403);
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'WRONG'})).status,400);
 const state=async()=>JSON.stringify({team:await prisma.fantasyTeam.findMany(),players:await prisma.player.findMany(),points:await prisma.userGameweekPoints.findMany(),squads:await prisma.userGameweekSquad.findMany()});const before=await state();
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'CLOSED'})).data.marketIsOpen,false);
 assert.equal((await request('/gameweeks/current',admin.id)).data.marketIsOpen,false);
 assert.equal((await request('/my-team/transfers',user.id)).data.marketIsOpen,false);
 assert.equal((await request('/my-team/players',user.id,'POST',{playerId:player.id})).status,423);
 await assert.rejects(()=>assertOpenMarket(prisma,true,new Date(),user.id),/LINEUP_MARKET_CLOSED/);
 assert.equal((await request('/gameweeks/current',user.id)).data.marketOverride,false);
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'OPEN'})).data.marketIsOpen,true);
 assert.equal((await request('/my-team/transfers',user.id)).data.marketIsOpen,true);
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'AUTO'})).data.marketOverride,null);
 assert.equal(await state(),before,'Market toggles must not change budget, prices, points or squads');
 assert.equal(await prisma.adminAuditLog.count({where:{action:'MARKET_UPDATED'}}),3);
 mock.timers.setTime(new Date('2026-10-03T10:00:00Z').getTime());
 week=(await request('/gameweeks/current',user.id)).data;assert.equal(week.marketIsOpen,false);
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'OPEN'})).data.marketIsOpen,true);
 assert.equal((await request('/my-team/players',user.id,'POST',{playerId:player.id})).status,201);
 await prisma.gameweek.update({where:{id:week.id},data:{status:'COMPLETED'}});
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'OPEN'})).status,409);
 mock.timers.setTime(new Date('2026-10-05T10:00:00Z').getTime());
 const next=(await request('/gameweeks/current',user.id)).data;assert.notEqual(next.id,week.id);assert.equal(next.marketOverride,null);assert.equal(next.marketIsOpen,true);
 assert.equal((await request('/admin/market',admin.id,'PATCH',{gameweekId:week.id,mode:'CLOSED'})).status,409);
 const winter=marketDatesForWeek(new Date('2026-11-04T12:00:00Z'));assert.equal(winter.marketOpenAt.toISOString(),'2026-11-02T07:00:00.000Z');assert.equal(winter.deadlineAt.toISOString(),'2026-11-06T18:00:00.000Z');
 const auto={...winter,status:'OPEN',marketOverride:null};assert.equal(marketIsOpen(auto,winter.marketOpenAt),true);assert.equal(marketIsOpen(auto,winter.deadlineAt),false);
 console.log('PASS: admin authorization, durable overrides, transactional purchase/lineup locks, audit, unchanged financial data, manual weekend opening, completed/stale rejection, weekly reset and DST. Isolated database:',database);
} finally {server.close();await prisma.$disconnect();mock.timers.reset();}
