import 'dotenv/config';
import { PrismaClient } from '@prisma/client';
import { spawnSync } from 'node:child_process';
import assert from 'node:assert/strict';
import jwt from 'jsonwebtoken';
import { once } from 'node:events';
const url = new URL(process.env.DATABASE_URL!);
assert.ok(['localhost', '127.0.0.1'].includes(url.hostname));
const database = `fantasy_matches_${Date.now()}`;
const setup = new PrismaClient();
await setup.$executeRawUnsafe(`CREATE DATABASE "${database}"`);
await setup.$disconnect();
url.pathname = '/' + database; process.env.DATABASE_URL = url.toString();
const migration = spawnSync(process.execPath, ['node_modules/prisma/build/index.js', 'migrate', 'deploy', '--schema', 'backend/prisma/schema.prisma'], { env: process.env, encoding: 'utf8' });
assert.equal(migration.status, 0, migration.stderr);
const { prisma } = await import('../src/lib/prisma.js');
const { app } = await import('../src/app.js');
const server = app.listen(0, '127.0.0.1'); await once(server, 'listening');
const port = (server.address() as { port: number }).port;
const request = async (path: string, userId: string, method = 'GET', body?: unknown) => {
  const token = jwt.sign({}, process.env.JWT_SECRET!, { subject: userId });
  const r = await fetch(`http://127.0.0.1:${port}/api${path}`, { method, headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, ...(body ? { body: JSON.stringify(body) } : {}) });
  return { status: r.status, data: await r.json() };
};
try {
 const admin=await prisma.user.create({data:{name:'Admin',email:'admin@match.invalid',passwordHash:'unused',role:'ADMIN'}});
 const user=await prisma.user.create({data:{name:'User',email:'user@match.invalid',passwordHash:'unused'}});
 const clubs=await Promise.all(['Home','Away'].map(name=>prisma.club.create({data:{name}})));
 const players=await Promise.all(Array.from({length:12},(_,i)=>prisma.player.create({data:{name:`Player ${i}`,number:i,clubId:clubs[i<6?0:1]!.id,position:i%6===0?'GOALKEEPER':'FIELD_PLAYER',role:i%6===0?'PORTERA':'ALA',price:4000}})));
 const week=await prisma.gameweek.create({data:{number:101,name:'Test',status:'LOCKED',startsAt:new Date('2026-01-01'),endsAt:new Date('2026-01-02'),marketOpenAt:new Date('2025-12-25'),deadlineAt:new Date('2026-01-01')}});
 const createBody={gameweekId:week.id,homeId:clubs[0]!.id,awayId:clubs[1]!.id,kickoffAt:null};
 assert.equal((await request('/matches',user.id,'POST',createBody)).status,403);
 const created=await request('/matches',admin.id,'POST',createBody);assert.equal(created.status,201);const id=created.data.id;
 assert.equal((await request('/matches',admin.id,'POST',createBody)).status,409);
 assert.equal((await request(`/matches/${id}/editor`,user.id)).status,403);
 const editor=await request(`/matches/${id}/editor`,admin.id);assert.equal(editor.status,200);
 const protocol={homeScore:2,awayScore:0,homeOwnGoals:0,awayOwnGoals:0,players:players.map((p,i)=>({playerId:p.id,started:i%6<5,goals:i===1?2:0,yellowCards:i===2?1:0,redCards:0,goalsConceded:i===0?0:i===6?2:null}))};
 const save=(version:number,publish:boolean,p=protocol)=>request(`/matches/${id}/editor`,admin.id,'PUT',{protocol:p,version,publish,kickoffAt:null});
 assert.equal((await save(0,false)).status,200);
 assert.equal(await prisma.playerGameweekStats.count(),0,'Draft must not award points');
 let publicMatch=(await request(`/matches/${id}`,user.id)).data;
 assert.equal(publicMatch.published,null);assert.equal('draft' in publicMatch,false,'Draft must remain private');
 assert.equal((await save(0,true)).status,409,'Reject stale writes');
 assert.equal((await save(1,true,{...protocol,homeScore:3})).status,400,'Reject score mismatch');
 const bad=structuredClone(protocol);bad.players[4]!.started=false;assert.equal((await save(1,true,bad)).status,400,'Require five starters');
 const duplicate=structuredClone(protocol);duplicate.players[1]!.playerId=duplicate.players[0]!.playerId;assert.equal((await save(1,true,duplicate)).status,400,'Reject duplicate players');
 await prisma.playerGameweekStats.create({data:{gameweekId:week.id,playerId:players[1]!.id,adjustmentPoints:3,adjustmentReason:'Preserve'}});
 await prisma.userGameweekSquad.create({data:{gameweekId:week.id,userId:user.id,fantasyTeamName:'Test',players:{create:players.slice(0,5).map(p=>({playerId:p.id,status:'STARTER'}))}}});
 assert.equal((await save(1,true)).status,200);
 const stat=await prisma.playerGameweekStats.findUniqueOrThrow({where:{gameweekId_playerId:{gameweekId:week.id,playerId:players[1]!.id}}});assert.equal(stat.totalPoints,17);assert.equal(stat.adjustmentPoints,3);
 const total=await prisma.userGameweekPoints.findUniqueOrThrow({where:{gameweekId_userId:{gameweekId:week.id,userId:user.id}}});assert.equal(total.totalPoints,37);
 assert.equal((await save(2,true)).status,200);assert.equal(await prisma.playerGameweekStats.count(),12,'Republish must not duplicate stats');
 const draft=structuredClone(protocol);draft.players[1]!.goals=3;draft.homeScore=3;assert.equal((await save(3,false,draft)).status,200);
 publicMatch=(await request(`/matches/${id}`,user.id)).data;assert.equal(publicMatch.published.homeScore,2,'Draft edits must not replace published score');
 assert.equal(publicMatch.published.players.find((p:{playerId:string})=>p.playerId===players[1]!.id).totalPoints,17);
 const legacy=await request(`/admin/gameweeks/${week.id}/players/${players[1]!.id}/stats`,admin.id,'PUT',{started:true,result:'WIN',goals:8,yellowCards:0,redCards:0,cleanSheet:false,goalsConceded:null});assert.equal(legacy.status,409,'Prevent protocol/stat divergence');
 assert.equal((await request('/matches/'+id,admin.id,'DELETE')).status,409,'Cannot delete published reports');
 const next=await prisma.gameweek.create({data:{number:102,name:'Next',status:'LOCKED',startsAt:new Date('2026-01-08'),endsAt:new Date('2026-01-09'),marketOpenAt:new Date('2026-01-03'),deadlineAt:new Date('2026-01-08')}});
 const nextMatch=await request('/matches',admin.id,'POST',{...createBody,gameweekId:next.id});assert.equal(nextMatch.status,201);
 const nextEditor=await request('/matches/'+nextMatch.data.id+'/editor',admin.id);assert.equal(nextEditor.data.previousStarters[clubs[0]!.id].length,5);
 assert.equal((await request('/matches/'+nextMatch.data.id,admin.id,'DELETE')).status,200);assert.equal(await prisma.matchTeam.count({where:{gameweekId:next.id}}),0);
 await prisma.gameweek.update({where:{id:week.id},data:{status:'COMPLETED'}});assert.equal((await save(4,true)).status,409);
 console.log('PASS: authorization, draft privacy, stale writes, validation, atomic scoring, adjustment preservation, repeat publication, public report and locked gameweek');
} finally {
 server.close();await prisma.$disconnect();
 const cleanup=new PrismaClient({datasources:{db:{url:process.env.DATABASE_URL!.replace('/'+database,'/postgres')}}});
 await cleanup.$executeRawUnsafe(`DROP DATABASE "${database}" WITH (FORCE)`);await cleanup.$disconnect();
}
